---
title: "Kenya Census"
date: "January 18, 2021"
output:
  workflowr::wflow_html:
    toc: no
    code_folding: hide
editor_options:
  chunk_output_type: console
---

# rKenyaCensus

The data this week was compiled by [Shel Kariuki](https://twitter.com/Shel_Kariuki) from results released by the Kenya National Bureau of Statistics in February 2020, originally published in four different pdf files (Volume 1 - Volume 4). Beyond the sample `#TidyTuesday` sets, I've pulled additional agricultural figures from her [web data portal](https://shel-kariuki.shinyapps.io/KenyaCensus2019/).

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	cache = FALSE,
	cache.lazy = FALSE,
	df_print = "paged",
	dpi = 300,
	tidy = "styler"
)

suppressPackageStartupMessages({
library(tidyverse)
library(tidytuesdayR)
library(hrbrthemes)
library(tweetrmd)
library(sf)
library(cartogram)
library(cowplot)

library(rKenyaCensus)

})
extrafont::loadfonts(quiet = TRUE)

theme_set(hrbrthemes::theme_ft_rc() +
            theme(plot.title.position = "plot",
                  plot.caption.position = "plot"))

```

```{r Load}

shapefiles <- rKenyaCensus::KenyaCounties_SHP %>% sf::st_as_sf()

households_with_crops <- rKenyaCensus::V4_T2.21
households_with_other_crops <- rKenyaCensus::V4_T2.22
households_with_livestock <- rKenyaCensus::V4_T2.23
livestock <- rKenyaCensus::V4_T2.24

# Distribution of area (hectares) of Agricultural land and Farming Households by purpose of production, County and Sub-County

ag <- rKenyaCensus::V4_T2.25 %>% 
    filter(AdminArea == "County") %>%   
    select(County, LandSize_Subsistence, LandSize_Commercial,
           No.FHS_Subsistence, No.FHS_Commercial) %>%
    mutate(AvgArea_Subsistence = 
           if_else(LandSize_Subsistence > 0.1,
                   No.FHS_Subsistence/LandSize_Subsistence,
                   NA_real_),
         AvgArea_Commercial = 
           if_else(LandSize_Commercial > 0.1,
                   No.FHS_Commercial/LandSize_Commercial,
                   NA_real_)) %>%   
      pivot_longer(-County,
                 names_sep = "_",
                 names_to = c("Metric","FarmType"))

ag_area_sf <- shapefiles %>% 
  inner_join(ag, by = "County") %>% 
  mutate(County = stringr::str_to_title(County)) 

landsize_dorling <-
  cartogram_dorling(
    x = filter(ag_area_sf,Metric == "LandSize"),
    weight = "value",
    k = 0.5,
    itermax = 100
  )

families_dorling <-
    cartogram_dorling(
    x = filter(ag_area_sf,Metric == "No.FHS"),
    weight = "value",
    k = 0.5,
    itermax = 100
  )
```


```{r maps}
landsize_dorling %>% 
  mutate(CountyLabel = if_else(value > quantile(filter(ag_area_sf,
                                                        Metric == "LandSize")$value, 0.9),County, NA_character_)) %>% 
    ggplot(aes(fill = value)) +
      geom_sf(color = NA) +
      geom_sf(data = filter(ag_area_sf, Metric == "LandSize"),
              color = "grey30", fill = NA, alpha = 0.5) +
  ggrepel::geom_text_repel(
    aes(label = CountyLabel, geometry = geometry),
    stat = "sf_coordinates",
    nudge_x = 0.5,
    nudge_y = 0.5,
    box.padding = 1,
    segment.curvature = -0.1,
    segment.ncp = 3,
    segment.angle = 20,
    arrow = arrow(length = unit(0.02, "npc")),
    family = "Roboto Condensed",
    size = 4,
    min.segment.length = 0,
    colour = "white",
    segment.colour = "white"
  ) +
  coord_sf(label_axes = "----") +
  facet_wrap(~ FarmType) +
  scale_fill_stepsn(colors = terrain.colors(5, rev = TRUE), 
                    n.breaks = 5,
                    label = scales::comma_format(),
                    trans = "log10", guide = "legend") +
  labs(x = NULL, y = NULL, fill = "Hectares Total",
       title = "Crop Farming in Kenya, by County",
       caption = "2019 Kenya Population and Housing Census") +
  theme(panel.grid.major =  element_blank(),
        legend.position = "bottom")

families_dorling %>% 
  mutate(CountyLabel = if_else(value > quantile(filter(ag_area_sf,
                                                        Metric == "No.FHS")$value, 0.9),County, NA_character_)) %>% 
    ggplot(aes(fill = value)) +
      geom_sf(color = NA) +
      geom_sf(data = filter(ag_area_sf, Metric == "No.FHS"),
              color = "grey30", fill = NA, alpha = 0.5) +
  ggrepel::geom_text_repel(
    aes(label = CountyLabel, geometry = geometry),
    stat = "sf_coordinates",
    nudge_x = 0.5,
    nudge_y = 0.5,
    box.padding = 1,
    segment.curvature = -0.1,
    segment.ncp = 3,
    segment.angle = 20,
    arrow = arrow(length = unit(0.02, "npc")),
    family = "Roboto Condensed",
    size = 4,
    min.segment.length = 0,
    colour = "white",
    segment.colour = "white"
  ) +
  coord_sf(label_axes = "----") +
  facet_wrap(~ FarmType) +
  scale_fill_stepsn(colors = terrain.colors(5, rev = TRUE), 
                    label = scales::comma_format(),
                    limits = c(5e4,2.5e5), n.breaks = 5,
                    guide = "legend") +
  labs(x = NULL, y = NULL, fill = "Households",
       title = "Crop Farming in Kenya, by County",
       caption = "2019 Kenya Population and Housing Census") +
  theme(panel.grid.major =  element_blank(),
        legend.position = "bottom")
  
ag_area_sf %>% 
  filter(Metric == "AvgArea") %>% 
  mutate(CountyLabel = if_else(value > quantile(filter(ag_area_sf,
                                                        Metric == "AvgArea")$value, 0.9),County, NA_character_)) %>% 
  ggplot() + 
  geom_sf(aes(fill = value), color = "grey30", alpha = 0.8) +
  ggrepel::geom_text_repel(
    aes(label = CountyLabel, geometry = geometry),
    stat = "sf_coordinates",
    nudge_x = 0.5,
    nudge_y = 0.5,
    box.padding = 1,
    segment.curvature = -0.1,
    segment.ncp = 3,
    segment.angle = 20,
    arrow = arrow(length = unit(0.02, "npc")),
    family = "Roboto Condensed",
    size = 4,
    min.segment.length = 0,
    colour = "white",
    segment.colour = "white"
  ) +
  coord_sf(label_axes = "----") +
  facet_wrap(~ FarmType) +
  scale_fill_stepsn(colors = terrain.colors(5, rev = TRUE), 
                    n.breaks = 5,
                    label = scales::label_number(), guide = "legend") +
  labs(x = NULL, y = NULL, fill = "Average \nFarm Size \nHectares",
       title = "Crop Farming in Kenya, by County",
       caption = "2019 Kenya Population and Housing Census") +
  theme(panel.grid.major =  element_blank(),
        legend.position = "bottom")

```




