---
title: "European Flights"
author: "Jim Gruman"
date: "July 13, 2022"
output:
  workflowr::wflow_html:
    toc: no
    code_folding: hide
    code_download: true
    df_print: paged
editor_options:
  chunk_output_type: console
---

In this weeks #TidyTuesday we take a look at the number of flights arriving and departing from several large European airports.

data is via Eurocontrol at [https://ec.europa.eu/eurostat/web/products-eurostat-news/-/ddn-20210914-1](https://ec.europa.eu/eurostat/web/products-eurostat-news/-/ddn-20210914-1)

```{r }
#| label: setup

suppressPackageStartupMessages({
library(tidyverse)
library(lubridate)
library(patchwork)
 })

source(here::here("code","_common.R"),
       verbose = FALSE,
       local = knitr::knit_global())

ggplot2::theme_set(grumanlib::theme_jim(base_size = 12))

```

Let's see what we can do to improve BrendiA's heatmap:

```{r}
tweetrmd::include_tweet("https://twitter.com/brendialj/status/1547206511910600706")
```


```{r}
#| label: load

tt <- tidytuesdayR::tt_load("2022-07-12")

flights <- tt$flights |> 
  rename(airport_label = `Pivot Label`) |> 
  janitor::clean_names() |> 
  select(-year, -month_num, -month_mon)

total_flights <- flights |> 
  group_by(flt_date) |> 
  summarise(total_dep = sum(flt_dep_1, na.rm = TRUE),
            .groups = "drop") |> 
  complete(flt_date = seq.Date(from = as_date("2022-01-01"),
                               to = as_date("2022-12-31"),
                               by = "day",
                               fill = list(value = NA))) |> 
    mutate(year = year(flt_date), 
         week_of_year = week(flt_date),
         month = month(flt_date, label = TRUE, abbr = TRUE),
         day = day(flt_date)
  )


```


```{r}
#| label: functions

# Function prepares data for plotting based on a given year by BrendiA at https://github.com/BrendiA/tidy-tuesday/blob/main/2022/week-28/week-28.R
create_df <- function(given_year) {
  
  # Extract first day of the week for the year
  first_day_of_year <-
    wday(as_date(paste(given_year, "01", "01", sep = "-")),
         week_start = 1)

  total_flights |> 
    filter(year == given_year) |> 
    mutate(day_of_week = wday(flt_date,
                              label = TRUE,
                              week_start = first_day_of_year)) |> 
#    mutate(day_of_week = forcats::fct_rev(day_of_week)) |>  
    group_by(month) |> 
    mutate(week_of_month = -1*dense_rank(week_of_year)) |> 
    ungroup()
}

best_contrast <- function(x, y = c("#010101","#FFFFFF")){
  contrasts <- prismatic::contrast_ratio(x, y)
  y[max(contrasts) == contrasts][1]
}

# Function plots heatmap based on the data generated by BrendiA at https://github.com/BrendiA/tidy-tuesday/blob/main/2022/week-28/week-28.R  with Emil Hvitfeldt's Prismatic text color adjustments
plot_heatmap <- function(df){
  
  # Year list of the data frame
  given_year <- unique(df$year)
  
  ggplot(data = df,
         aes(y = week_of_month, 
             x = day_of_week,
             fill = total_dep)) +
    # Heat map
    geom_tile() +
    # Calendar days
    geom_text(aes(label = day,
                  color = ggplot2::after_scale(purrr::map_chr(fill, best_contrast))),
              size = 2) +
    colorspace::scale_fill_continuous_sequential(name = "Number of departures",
                                                 palette = "Viridis",
                                                 na.value = "grey60", # Fill missing dates
                                                 limits = c(0, 30000),
                                                 breaks = seq(0, 30000, 10000),
                                                 oob = scales::squish,
                                                 label = scales::label_comma(accuracy = 1),
                                                 c2 = 60, # increase
                                                 l1 = 10) + # decrease
    facet_wrap(~ month,
               nrow = 1) +
    theme_minimal() +
    labs(title = given_year) +
    theme(
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.title = element_blank(),
      legend.direction = "horizontal",
      legend.key.width = unit(1.5, "cm"),
      legend.text = element_text(family = "Regular 400"),
      legend.title = element_text(vjust = 0.8, family = "Regular 400"),
      panel.spacing.x = unit(0, "lines"),
      panel.grid = element_blank(),
      plot.title = element_text(hjust = 0.5, family = "Black 900 Italic", size = 12, face = "bold"),
      strip.text = element_text(family = "Regular 400", size = 8)
    ) 
}

```

```{r}

plot_list <- 
  purrr::map(unique(sort(total_flights$year)),
             ~ create_df(.x) |> 
               plot_heatmap())

```

The functions above create a big list of heat maps, one for each year. I've added prismatic contrasts to the geom_text to make the dates just a bit more legible. 


```{r}
#| fig.asp = 1

# Subtitle 
sub <-
  str_wrap(
    "The aviation industry took a toll on the Covid-19 pandemic. 
    There are signs of recovery, with commercial flights in the EU increasing from mid-June 2021. 
    Will the rest of 2022 see a total number of departures close to pre-pandemic levels?",
    width = 90
  )

plot_list[[3]] + 
  plot_list[[4]] + 
  plot_list[[5]] + 
  plot_list[[6]] +
  plot_list[[7]] +
  plot_layout(guides = "collect",
              ncol = 1,
              height = 0.5) &
  plot_annotation(
    title = "Commercial flight departures in the EU",
    subtitle = sub,
    caption = "Source: Eurocontrol | #TidyTuesday Week 28 | @brendialj with the heatmap concept",
    theme = theme(
      legend.position = "bottom",
      plot.title = element_text(hjust = 0.5, size = 18, face = "bold"),
      plot.subtitle = element_text(hjust = 0.5, size = 14),
      plot.background = element_rect(fill = "#f0f8ff"),
      plot.caption = element_text(vjust = 1)) 
  )
```

