---
title: "Coffee"
author: "Jim Gruman"
date: 'July 7, 2020'
output:
  workflowr::wflow_html: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE, 
                      fig.showtext = T, 
                      fig.width = 9,
                      fig.height=6)
```

```{r prep, message=FALSE}
library(tidyverse)
library(ggridges)

library(widyr)
library(ggraph)
library(igraph)
library(tidytext)

theme_set(hrbrthemes::theme_ipsum())

```

```{r}
coffee <- tidytuesdayR::tt_load("2020-07-07")

coffee_ratings <- coffee$coffee_ratings %>%
  mutate(coffee_id = row_number(),
         country_of_origin = case_when(stringr::str_detect(country_of_origin,"Tanzania")~ "Tanzania",
          stringr::str_detect(country_of_origin,"Hawaii")~ "US Hawaii",                            TRUE ~ country_of_origin)) %>%
  filter(total_cup_points > 0) 
```

```{r}
coffee_ratings %>%
  count(species, sort = TRUE) %>%
  knitr::kable()

coffee_lumped <- coffee_ratings %>%
  filter(!is.na(variety)) %>%
  mutate(variety = fct_lump(variety, 8), sort = TRUE)

coffee_lumped %>%
  mutate(variety = fct_reorder(variety, total_cup_points)) %>%
  ggplot(aes(total_cup_points, variety)) +
  geom_boxplot(color = "#d95f0e")+
  theme(plot.title.position = "plot")+
  labs(title = "Coffee Quality Ratings",
       caption = "https://github.com/jldbc/coffee-quality-database",
       x = "Total Cup Points",
       y = "Coffee Variety")

coffee_lumped %>%
  ggplot(aes(total_cup_points, fill = variety)) +
  geom_histogram(binwidth = 2) +
  facet_wrap(~ variety, scale = "free_y") +
  theme(legend.position = "none",
        plot.title.position = "plot")+
  labs(title = "Coffee Quality Ratings",
       caption = "https://github.com/jldbc/coffee-quality-database",
       x = "Total Cup Points",
       y = "Number of Submissions")
```

```{r}
coffee_ratings %>%
  summarize(across(everything(), ~ mean(!is.na(.)))) %>%
  gather() %>%
  arrange(desc(value))%>%
  knitr::kable()

coffee_ratings %>%
  filter(!is.na(producer))%>%
  mutate(producer = fct_lump(producer, 20))%>%
  count(producer, sort = TRUE) %>%
  knitr::kable(caption = "Count of Coffee Samples by")

coffee_ratings %>%
  filter(!is.na(company))%>% 
  mutate(company = fct_lump(company, 20))%>%
  count(company, sort = TRUE)%>%
  knitr::kable(caption = "Count of Coffee Samples by")

coffee_ratings %>%
  filter(!is.na(color))%>% 
  count(color, sort = TRUE)%>%
  knitr::kable(caption = "Count of Coffee Samples by")

coffee_ratings %>%
  count(country = fct_lump(country_of_origin, 12), sort = TRUE) %>%
  filter(!is.na(country)) %>%
  mutate(country = fct_reorder(country, n)) %>%
  ggplot(aes(n, country)) +
  geom_col(fill = "#d95f0e")+
  theme(plot.title.position = "plot")+
  labs(title = "Coffee Quality Ratings",
       caption = "https://github.com/jldbc/coffee-quality-database",
       x = "Number of Submissions",
       y = "")

coffee_ratings %>%
  filter(!is.na(country_of_origin)) %>%
  mutate(country = fct_lump(country_of_origin, 12),
         country = fct_reorder(country, total_cup_points)) %>%
  ggplot(aes(total_cup_points, country)) +
  geom_boxplot(color = "#d95f0e") +
  theme(plot.title.position = "plot")+
  labs(title = "Coffee Quality Ratings",
       caption = "https://github.com/jldbc/coffee-quality-database",
       x = "Total Cup Points",
       y = "")
```


```{r}
coffee_metrics <- coffee_ratings %>%
  dplyr::select(coffee_id, total_cup_points, variety, company,
         country_of_origin,
         altitude_mean_meters,
         aroma:moisture) %>%
  pivot_longer(aroma:cupper_points, names_to = "metric", values_to = "value")

coffee_metrics %>%
  mutate(metric = fct_reorder(metric, value)) %>%
  ggplot(aes(value, metric)) +
  geom_density_ridges(fill = "#d95f0e")+
  scale_x_continuous(limits = c(5,10.2))+
  theme(plot.title.position = "plot")+
  labs(title = "Coffee Quality Ratings",
       caption = "https://github.com/jldbc/coffee-quality-database",
       x = "Score",
       y = "")

coffee_metrics %>%
  group_by(metric) %>%
  summarize(average = mean(value),
            sd = sd(value)) %>%
  arrange(desc(average)) %>%
  knitr::kable()
```

```{r, fig.height=7}
correlations <- coffee_metrics %>%
  pairwise_cor(metric, coffee_id, value, sort = TRUE)

correlations %>%
  head(50) %>%
  graph_from_data_frame() %>%
  ggraph() +
  geom_edge_link(aes(edge_alpha = correlation),show.legend = FALSE ) +
  geom_node_point() +
  geom_node_text(aes(label = name), repel = TRUE)+
  theme(plot.title.position = "plot")+
  labs(title = "Coffee Quality",
       subtitle = "Network Diagram of Attribute Correlation",
       caption = "https://github.com/jldbc/coffee-quality-database",
       x = "",
       y = "")

coffee_metrics %>%
  filter(!metric %in% c("sweetness", "clean_cup", "uniformity")) %>%
  group_by(metric) %>%
  mutate(centered = value - mean(value)) %>%
  ungroup() %>%
  widely_svd(metric, coffee_id, value) %>%
  filter(between(dimension, 1, 6)) %>%
  mutate(metric = reorder_within(metric, value, dimension)) %>%
  ggplot(aes(value, metric)) +
  geom_col( fill = "#d95f0e") +
  scale_y_reordered() +
  facet_wrap(~ dimension, scales = "free_y")+
  theme(plot.title.position = "plot")+
  labs(title = "Coffee Quality",
       subtitle = "Principal Components of Attributes",
       caption = "https://github.com/jldbc/coffee-quality-database",
       x = "",
       y = "")
```

```{r}
coffee_ratings %>%
  filter(altitude_mean_meters < 10000,
         altitude != 1) %>%
  mutate(altitude_mean_meters = pmin(altitude_mean_meters, 3500)) %>%
  ggplot(aes(altitude_mean_meters, total_cup_points)) +
  geom_point(color = "#d95f0e", alpha = 0.3) +
  geom_smooth(method = "lm")+
  theme(plot.title.position = "plot")+
  labs(title = "Coffee Quality",
       caption = "https://github.com/jldbc/coffee-quality-database",
       x = "Altitude (meters)",
       y = "Total Cup Points")

coffee_metrics %>%
  filter(altitude_mean_meters < 10000) %>%
  mutate(altitude_mean_meters = pmin(altitude_mean_meters, 3000)) %>%
  mutate(km = altitude_mean_meters / 1000) %>%
  group_by(metric) %>%
  summarize(correlation = cor(altitude_mean_meters, value),
            model = list(lm(value ~ km))) %>%
  mutate(tidied = map(model, broom::tidy, conf.int = TRUE)) %>%
  unnest(tidied) %>%
  filter(term == "km") %>%
  ungroup() %>%
  mutate(metric = fct_reorder(metric, estimate)) %>%
  ggplot(aes(estimate, metric, color = p.value < .05)) +
  geom_point() +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = .1) +
  theme(plot.title.position = "plot",
        legend.position = "top",
        legend.spacing.x = unit(6, "mm"),
        panel.grid.major.y = element_blank())+
  labs(title = "Coffee Quality",
       y = "Evaluation of coffee",
       x = "Each kilometer of altitude contributes\n this much to score (95% confidence interval)",
       caption = "https://github.com/jldbc/coffee-quality-database")
```

```{r}
coffee_lumped%>%
  mutate(country_of_origin = fct_lump_lowfreq(country_of_origin, 8)) %>%
  group_by(country_of_origin, variety) %>%
  summarise(score = mean(total_cup_points)) %>%
  ungroup()%>%
  filter(!variety %in% c("Other", "Yellow Bourbon")) %>%
  mutate(country_of_origin = reorder_within(country_of_origin, score, variety)) %>%
  ggplot()+
  geom_col(aes(x=score, 
              y=country_of_origin, 
              fill = ggplot2::cut_width(score,2)), show.legend = FALSE)+
  scale_fill_brewer(type = "seq", palette = "YlOrBr") +
  scale_y_reordered() +
#  scale_fill_brewer(type= "seq", palette = "YlOrBr")+
  theme(plot.title.position = "plot")+
  labs(title = "Mean Coffee Quality Total Cup Points",
       y = "", x = "Variety",
       caption = "#TidyTuesday 2020-07-07 @Jim_Gruman\n https://github.com/jldbc/coffee-quality-database")+
  facet_wrap(~ variety,  scales = "free_y")

```

***

```{r session}
Sys.time()
git2r::repository()
sessionInfo()
```