---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Welcome to my TidyTuesday website collection.

|   |   |   |    
|---|---|---|
|September 24, 2020| [Hops](Hops.html)| {rnassqs, blscrapeR}|
|September 22, 2020 | [Himalayan Climbers](HimalayanClimbers.html) | {ebbr, ggdark} |
|September 15, 2020 | [Kids Health Spending](KidsSpending.html) | {geojsonio, rgeos}| 
|September 8, 2020 | [Friends](Friends.html) | {tidytext, tidylo}|
|August 31, 2020 | [Crop Yields](CropYields.html) | {ggrepel}|
|August 11, 2020 | [Last Airbender](LastAirbender.html) | {tidytext, tidylo, textfeatures}|
|July 15, 2020 | [Astronaut Missions](Astronaut.html) | {tidymodels, baguette}|
|March 17, 2020 | [The Office](TheOffice.html) |  {tidymodels, tidytext}|
|July 7, 2020 | [Coffee](Coffee.html) | {widyr, tidytext}|
|May 5, 2020 | [Animal Crossing](AnimalCrossing.html) | {tidytext, stm, textrecipes, vip} topic modeling|
|April 21, 2020 | [GDPR Fines](GDPRfines.html) | {ggbeeswarm, rnaturalearth, tidymodels}|
|March 31, 2020 |[Beer Production](BeerProduction.html) | {gghighlight, tidymetrics}|
|March 24, 2020 | [Brain Injury](BrainInjury.html) | {gganimate, vip, tidymodels}|
|March 10, 2020 | [College Tuition](CollegeTuitionandDiversity.html) | {tidymodels}|
|February 4, 2020 | [NFL Attendance](NFLattendance.html) | {tidymodels} |
|November 26, 2019 | [Student Debt](StudentDebt.html) | {cowplot, ggrepel, dygraphs}|

  













