---
title: "Global Transit Costs"
author: "Jim Gruman"
date: "January 6, 2021"
output: 
  workflowr::wflow_html:
    toc: no
    code_folding: hide
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE, 
                      warning = FALSE)
```

```{r libraries}
suppressPackageStartupMessages({
library(tidyverse)
library(tidytuesdayR)
library(scales)
library(ggrepel)
library(ggtext)
library(countrycode)
library(shiny)
library(glue)
library(here)
library(showtext)
library(thematic)
})

theme_set(theme(plot.title.position = "plot", 
                plot.caption.position = "plot"))

thematic_shiny(bg = "#FFFFF8", fg = "#111111", 
             accent = "#DD1144", font = "Teko",
             qualitative = RColorBrewer::brewer.pal(3, "Dark2"))
```

```{r load}
transit_cost <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-05/transit_cost.csv')

```

```{r preparation2}
# transit_cost <- transit_cost[transit_cost$e > 0,] 

transit_cost <- transit_cost %>%
  dplyr::filter(!is.na(`e`)) %>% 
  dplyr::mutate(real_cost = as.numeric(real_cost)/1000,
         country_code = dplyr::if_else(country == "UK", "GB", country),
         country = countrycode(country_code, "iso2c", "country.name"),
         station_density = stations / length) %>%
  dplyr::mutate(country = forcats::fct_infreq(country))
```

```{r setMetrics}
metrics <- c("Track Length (km)" = "length",
             "Tunnel Length (km)" = "tunnel",
             "Stations" = "stations")
```
             
```{r mainChunk, eval = FALSE}
inputPanel(
  selectizeInput("country", 
                 label = "Country:",
                 choices = str_remove(levels(transit_cost$country), "United States"), 
                 selected = "China"),
  selectInput("metric", 
              label = "Metric:", 
              choices = metrics,
              selected = metrics[1])
)

transit_cost_country <- reactive({
  transit_cost 
})

renderPlot({
  us_color <- RColorBrewer::brewer.pal(3, "Dark2")[1]
  other_color <- RColorBrewer::brewer.pal(3, "Dark2")[2]

  metric <- input$metric
  x_axis_lab <- names(metrics)[metrics == metric]
  
transit_cost_country() %>%
    dplyr::filter(.data[[input$metric]] > 1,
           real_cost > 0.1) %>% 
    mutate(countrycolor = case_when(
      country == input$country ~ 1,
      country == "United States" ~ 2,
      TRUE ~ 3
    ),
    suffix = case_when(
      metric == "length" ~ paste0("$",round(cost_km_millions,1),"/km"),
      metric == "stations" ~ paste0(round(station_density,1),"/km"),
      metric == "tunnel" ~ paste0("$",round(cost_km_millions,1),"/km"),
      TRUE ~ NA_character_
    ),
    label = if_else((country == "United States" | country == input$country),
                    glue("{city}\n{suffix}"),
                    NA_character_)
    ) %>% 
    ggplot(aes(.data[[input$metric]], 
               real_cost, 
               color = case_when(
                 countrycolor == 1 ~ other_color,
                 countrycolor == 2 ~ us_color
                 ),
               label = label)) +
    geom_point() +
    geom_text_repel(size = 3, 
                    segment.color = "#f8f8f2", 
                    max.overlaps = 10,
                    segment.alpha = 0.7) +
    scale_y_log10() +
    scale_x_log10() +
    labs(x = x_axis_lab,
         y = "Billion USD",
         color = "Country") +
    theme(legend.position = "",
          plot.title = element_markdown(size = 22, hjust = 0, 
                                        lineheight = 1.2, 
                                        margin = margin(1, 0, 0, 0, unit = "line")),
          plot.subtitle = element_markdown(size = 18, hjust = 0, 
                                     lineheight = 1.4, 
                                     margin = margin(1, 0, 0, 0, unit = "line")),
    axis.title.x = element_text(margin = margin(1, 0, 0.5, 0, unit = "line")),
    axis.title.y = element_text(angle = 90, vjust = 0.5),
    panel.grid.major.y = element_line(color = "#44475a", size = 0.3),
    panel.grid.major.x = element_line(color = "#44475a", size = 0.3),
    panel.grid.minor.y = element_blank(),
    panel.grid.minor.x = element_blank()
          ) +
    labs(title = "Investment in Mass Transit in the 21<sup>st</sup> Century",
         subtitle = glue::glue("The <span style='color:{us_color};'>United States</span> has allocated $57B to 13 urban rail projects, mostly in New York and<br />California. No project exceeds 10 km and the most expensive project costs $11B<br /> for 2.8km of railway. In comparison,  <span style='color:{other_color};'>{ input$country }</span> has allocated over ${ format(sum(transit_cost$real_cost[transit_cost$country == input$country]), digits = 0) }Bn to { sum(transit_cost$country == input$country) } <br />urban rail projects, the longest of which runs { max(transit_cost$length[transit_cost$country == input$country]) }km and costs ${round(max(transit_cost$real_cost[transit_cost$country == input$country]),1)}Bn."), 
    y = "Billions of $ US", x = x_axis_lab,
    caption = "Data from transitcosts.com | @jim_gruman")

},
height = 1100
)

```

<iframe width="800" height="1200" src="https://jimgruman.shinyapps.io/transitcost/" data-size="full-width" ></iframe>
